# Generated by Django 5.2.8 on 2025-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='explanation',
            field=models.TextField(default='Respuesta correcta', help_text='Explica por qué esta es la respuesta correcta'),
        ),
    ]
