# Generated by Django 5.2.8 on 2025-12-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='points_reward',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='Nuevo Ejercicio', max_length=255),
        ),
    ]
